### ISSUE TITLE
Support for templates

### ISSUE THREAD

**Issue by RyanElfman** [jirikavi/AngularJS-Toaster#10]
Original question: Is it possible to have support for templates? I'd like to use this but provide my own HTML instead of what the original toaster is using. It would be nice to be able to replace {{toaster.body}} with a specific template.

EDIT
I noticed there is code for toaster.html in there but is it possible to specify a template?

**Comment by danieljsinclair** [comment]
Is there no way to pass data from the pop() method that can be used when the template is rendered? I notice that body and bodyTemplate unfortunately get combined. It would be useful when using the ng-included template if there were a way to pass data through to the scope. An extra parameter on the end of the pop function that takes an object such as "{ name: 'dave', message:'user not found' }" would be useful so that the template could bind to {{name}} and {{message}} accordingly.
