### ISSUE TITLE
Get global toaster count externally

### ISSUE THREAD

**Issue by yan-kisen** [jirikavi/AngularJS-Toaster#107]
It would be nice to be able to count the amount of toasters at any given time.

I want to limit the amount of toasters, especially if recovering from a loop. This would be different than setting the 'limit' option to 1, because the time delay between create/clear creates a jumping effect.

I think that it may be as easy as calling  $rootScope.$emit('toaster-removeToast'), and setting up an external count listening for 'toaster-removeToast' and 'toaster-newToast'

Additional, another cool feature would be adding the toaster, or at least the type as an argument to these events.

Currently I'm able to accomplish this with $('.toast-error').length, but not everyone wants to use jQuery.

Thanks

**Comment by Stabzs** [comment]
I wanted to return to this issue since it's related to two of the other open issues. 

Since each toast container is registered independently of other toast containers, it would be difficult to ascertain the number of toasts that exist at a time, since you'd have to broadcast to all available toaster containers and wait for the responses and you wouldn't know if/when you could safely resolve those calls to make sure that you had all existing containers.

Perhaps a better alternative would be to expand `toasterEventRegistry` to give more information about the state of registered handlers.  If an additional API call was added to this factory, it could be used to "query" all registered handlers about the current state of their attached toaster containers.  This of course would have to be a blocking, broadcasted event from the `toaster` service since that is how all all events currently work.  This particular event might want to be listened for in the `toasterEventRegistry`, since that way it could easily ensure a response from all registered handlers.

I'm open to any additional suggestions on better alternatives to this type of approach. While it's a bit of an edge case, I understand the desire to be able to do this type of thing.

**Comment by Stabzs** [comment]
After additional consideration, I do not believe that there is enough of a use case here to warrant adding it to the API. If this type of query is truly needed, the DOM can be manually checked.
