### ISSUE TITLE
Toaster close button always true in click handler if the toast showCloseButton is set

### ISSUE THREAD

**Issue by maybeswap** [jirikavi/AngularJS-Toaster#122]
I have been using version 0.4.10 in a project. In this version, the click handler accurately determined if one had clicked the "close" button or had just clicked the toast itself. 

You could see this in the template, with: ng-click="click(toaster, true)" called on the close button.

In the version 0.4.13, the close button has no such parameter in the template, and the consuming click handler checks the showCloseButton property of the toast. This makes it impossible to distinguish between someone who clicked the close button directly, or just the surrounding toast.

**Comment by Stabzs** [comment]
@maybeswap @jirikavi can we verify this fixed as of 0.4.14 and close please?

**Comment by developerashu** [comment]
As the current solution satisfy the need for having one button other than close button. But i have need to use multiple types of buttons in toast. So, Could you please make the custom parameter to receive in clickHandler function. So, On that basis i could make the logics there for which button was clicked and fire the events accordingly ? 
or QuickFix : If we return $event in clickHandler as third parameter so that we can make some logic on basis of class name from event.target ? (Attached image showing the need for three buttons)
![image](https://user-images.githubusercontent.com/31619923/70777880-e612f480-1da6-11ea-93f9-3a443b6ea9d7.png)
