### ISSUE TITLE
On PHP form submit

### ISSUE THREAD

**Issue by chad112** [jirikavi/AngularJS-Toaster#124]
Hi! This is more on the side of misunderstanding. I can't figure out a way to call Toaster on a PHP form submit, or when there's a certain location hash (blahblah.com/#success). Do you have any advice on making that work?

**Comment by Stabzs** [comment]
You would not be able to call it on a full page submit, since you'd have a full page load.  What you COULD do is create an onLoad handler that scraped the URL, looked for pertinent information (such as #success) and build a toast notification and popped it.  Keep in mind that if you wanted to do something like this you would also need to embed title and body into the query string if you needed those as well.  In this case, it would be easier to submit your form via ajax and pop your toast in the success callback of your ajax post.

**Comment by chad112** [comment]
Thanks for the reply! I got it working.. i appreciate the help :)

Chad
