### ISSUE TITLE
Question: Is it possible to disable animations so that angular-animate is not required?

### ISSUE THREAD

**Issue by germanger** [jirikavi/AngularJS-Toaster#125]
Can I somehow disable animations so that I dont require to inject angular-animate in my module?

**Comment by jirikavi** [comment]
Hi, this is not currently possible.

**Comment by germanger** [comment]
Do you think it would be too difficult to implement this?
Like this module: `angular-growl-2` https://github.com/JanStevens/angular-growl-2

In which:
If the application has injected `ngAnimate`, then the notifications are shown/hidden with animations
If the application doesn`t inject `ngAnimate`, the notifications are simply shown/hidden without animations

**Comment by Stabzs** [comment]
No, this is not difficult to implement whatsoever.  However, it is a very fundamental shift in perspective towards the importance of animations in the library.  As it stands now, ngAnimate is an explicitly required dependency for the library to function correctly and it tells the consumer exactly what is needed in order to work properly.  If this change were made, it would be up to the end user to choose whether or not they wanted the full experience and they would be fully responsible for ensuring it was properly loaded.

I don't think that there's necessarily a right or wrong answer.  It's just something that needs to be taken into account.  @jirikavi if you're comfortable with this change I'm happy to create the pull request for it.

**Comment by germanger** [comment]
I think it gives a plus to the project, like: "if you want animations inject ngAnimate, if not, don't inject it"

**Comment by jirikavi** [comment]
That is a nice feature so if you have time to create a pull request then I will merge it.
Jiri.

**Comment by Stabzs** [comment]
@jirikavi @germanger Done.  Documentation has been updated in the pull request to reflect the changes.

**Comment by germanger** [comment]
Nice!

**Comment by germanger** [comment]
is this change going to be accepted?

**Comment by Stabzs** [comment]
@germanger  This has been merged into the build.  Can you please verify the fix and close if resolved?

**Comment by germanger** [comment]
Ok, I will try it :)

**Comment by Stabzs** [comment]
It was updated, under the Animations section at the end of the README.  Please let me know if it isn't clear enough :)

**Comment by germanger** [comment]
Thanks a lot, it works like a charm.
I finally don't need ngAnimate any more! which was making other libraries (`ng-grid`) work with bugs.

Also bootstrap-ui modals now close faster without that dumb fade out.

**Comment by Stabzs** [comment]
@germanger Glad it worked for you!  I closed the issue since it appeared that the only outstanding potential questions were around documentation, but thank you for the confirmation.
