### ISSUE TITLE
Load toaster in factory

### ISSUE THREAD

**Issue by shaltie** [jirikavi/AngularJS-Toaster#145]
Hello
Is there any way to load toaster in factory?

I do:
app.factory('GetData', ['$http', '$q', '$rootScope', '$location', 'toaster',
	function($http, $q, $rootScope, $location, toaster) {
        ...
}
And I have an error;
Error: [$injector:unpr] Unknown provider: toasterProvider <- toaster <- GetData

In controllers works good.

**Comment by Stabzs** [comment]
You probably have a registration within your app module.  There is no reason why you would not be able to inject toaster into a factory.  

Your app declaration should look like the following:

```js

var app = angular.module('app', ['toaster']);

app.factory('GetData', ['$http', '$q', '$rootScope', '$location', 'toaster',
    function($http, $q, $rootScope, $location, toaster) {
    ...
}]);
```

**Comment by ybrodsky** [comment]
I am having a similar issue

```
crmApp.run(function(toaster) {
	toaster.pop('success', "title", "text");
})
```
I get no error, but the toaster never appears

**Comment by Stabzs** [comment]
@ybrodsky  This isn't an issue with the toaster library, but rather a timing issue directly related to when `.run()` is called.

You can think of `.run()` as something similar to a `main` method or entrance point in an AngularJS application.  It's called after `.config` and before directive compile functions, the main app controller, and directive link functions.

As a result, if you are trying to inject and immediately pop a toast in the `.run()` function, the digest cycle wouldn't be complete and, in fact, the toaster directive wouldn't even yet be discovered to act upon the toaster service!

If you want to do this type of thing, you should do so in the main application controller, no earlier (and even then depending on your timing you could run into issues).

Hopefully that helps.

**Comment by ybrodsky** [comment]
@Stabzs thanks for the reply.
What you say makes sense, but how come there's no warning or crash since I am trying to use a directive that's not yet loaded? Besides, if this were the case, it would simply not work and as I mentioned, the toaster inside the callback does show. Another thing I did, was to put a delay before firing the toaster, enough time for the whole app to load. Again, the same problem happened.

Anyway, I can see that this is beyond the plugin itself, but I figure you might have some idea as to what is happening. 
Thanks again.

**Comment by Stabzs** [comment]
@ybrodsky There's no warning since all that pop does is fire off an event.  The event is fired, but the directive is not yet loaded to actually receive the event.  As a result, there's no error but there's also no toast.

Now, as for the callback, that's wrapped in a timeout of sorts and I believe it's occurring in a separate digest cycle, although I haven't actually confirmed this fact.  My best guess is that it'll have given the original digest cycle (where run is contained) enough time to finish and the directive is ready to receive the second toast.

As for the delay IN the run function, without seeing a repo, it sounds like it would simply just hold up the end of the digest cycle, resulting in the same issue.

**Comment by ybrodsky** [comment]
@Stabzs I see. Well, thanks for the help and the explanation.

Regards.
