### ISSUE TITLE
prevent-duplicates option does not work for list of toasters

### ISSUE THREAD

**Issue by vasyldemchuk** [jirikavi/AngularJS-Toaster#148]
Hi,
I have faced the problem when I have list of toasters and I need to prevent duplicates. 
Unfortunately it does not work now as it always checks only the latest item in array (see attached photo)
![image](https://cloud.githubusercontent.com/assets/12528341/9430169/b7c086d2-49f3-11e5-8035-f944c50e948a.png)

Instead of checking only the latest item it should loop the whole array. Does not it? 
Please let me know when this can be fixed..

Thank you!

**Comment by Stabzs** [comment]
This is not necessarily a defect.  If you look at the toastr library, https://github.com/CodeSeven/toastr/blob/master/toastr.js, which is what AngularJS-Toaster was ported from, the functionality is identical.  preventDuplicates does not prevent ANY duplication in the toast array, but rather just the last toast (useful for accidental double firing from double-clicking, etc).

If this is a needed feature, rather than destroying the original functionality, it would make sense to expand the functionality in a new way (`prevent-any-duplicates`).

**Comment by vasyldemchuk** [comment]
I do not think this is going to destroy something in original functionality. Instead of simple checking the latest  toaster it could loop the whole array. It will allow to keep existing functionality and expand it for new purpose (as you called it - prevent-any-duplicates).
See suggested pull request (https://github.com/jirikavi/AngularJS-Toaster/pull/149)
I still believe it can be done inside one option (prevent-duplicates). Do not see any reason to add new option and do this library so user-confused.

**Comment by Stabzs** [comment]
The original functionality explicitly did not check the entire array however, so the intent of the library WOULD mutate.  I'm not arguing that this is a bad change; in fact, it would probably be useful.  However, it is a very conscientious move from the original functionality of the library and it's predecessor and the impacts of that should be very clear before proceeding.

**Comment by vasyldemchuk** [comment]
Is this library so tied to original one? I thought this is absolutely another, just similar library.

Let me explain the reason why I am asking about these changes. 
I have the situation when I need to display several alerts (depends on some rules) using body-output-type: 'templateWithData'.
Template contains two buttons, say "Allow" and "Deny". 
For instance, we have two alerts with two buttons inside each of them. My aim is to force user to pick up the suggested option (Allow or Deny). So when he still ignores these alerts and goes to another page I need to display alerts again. 
When I have only one alerts, then it works nicely, but for multiple alerts it just duplicates existing ones. 
NOTE: I cannot use toastId option and remove existing toasts from array and add them back due to animation.

I believe this is not rarely problem and a lot of developers who use this library will appreciate new changes.

**Comment by vasyldemchuk** [comment]
Any updates? Is it going to be released soon?

**Comment by Stabzs** [comment]
Since no-one has raised any additional concerns, it seems like this is a reasonable change to make.  If someone down the road does not want full-array duplication checks, an optional flag can be added to distinguish behaviors, as I mentioned above.

Your merge request is missing the minified javascript.  Please minify and I'll approve the merge request.
