### ISSUE TITLE
Close button error on read me.

### ISSUE THREAD

**Issue by ZSnake** [jirikavi/AngularJS-Toaster#151]
Hey guys, on your read.me you explain that to configure the close button globally you can use 
`<toaster-container toaster-options="'close-button': true"></toaster-container>`

But that gave me the following error
`Error: [$parse:syntax] Syntax Error: Token ':' is an unexpected token at column 15 of the expression ['close-button': true] starting at [: true].
http://errors.angularjs.org/1.4.7/$parse/syntax?p0=%3A&p1=is%20an%20unexpected%20token&p2=15&p3='close-button'%3A%20true&p4=%3A%20true`

So, what I did was to add brackets to the close-button option like this:
`<toaster-container toaster-options="'{close-button': true}"></toaster-container>`. 

It's a notification more than a bug :)

**Comment by Stabzs** [comment]
Whoops! The documentation actually has a small typo for the first close-button configuration (applying one configuration for all types) as opposed to the second example where behavior is being applied per toast type.

It SHOULD read:

`<toaster-container toaster-options="{'close-button': true}"></toaster-container>`

since options is an object.  I'll update the documentation.  Thank you for pointing it out!

**Comment by Stabzs** [comment]
This has been fixed in pull request #152.  There was an additional error in the documentation that would have caused the same behavior.  Thank you again for pointing it out.
