### ISSUE TITLE
Pass data to directive?

### ISSUE THREAD

**Issue by azaslavsky** [jirikavi/AngularJS-Toaster#153]
Would it be possible to add functionality to somehow pass data to the directive when `bodyOutputType: "directive"`?

**Comment by Stabzs** [comment]
How would you expect this to work?  How would you control the data flow? Where would data come from and why would the toast own that data in the first place?

Personally, I think it would be far better to use a shared service between code that fires the toast and your target directive.  This seems like it would place control in the proper place, the directive, and allow it to "pull" what it needs rather than having arbitrary data pushed to it.

**Comment by azaslavsky** [comment]
Ok, I have a notification directive which seeks to render the following:

"Hi, {username}, welcome to my app!"

Usually, I would make a template with `{{username}}` somewhere inside of it, then pass the username property to my directive scope when I initialize it.  As of now, that workflow is not possible, because I cannot pass data into the directive scope, which is how almost every other directive I've ever used works.  It seems to me like it's not that useful to have the directive option at all if it ends up being a fancy way to load a static template anyway.

Perhaps a property in `.pop()`'s options, something like `toastDirectiveData`, which would be passed into the directive's isolate scope?  So, in my directive itself, I could just set the property  `scope: {toastDirectiveData: '?='}` and it would grab the whatever data I passed in to `toastDirectiveData`?  Seems like a reasonable change to me.

**Comment by Stabzs** [comment]
This feature has been added and merged, as well as some other useful error-checking enhancements for directiveTemplate.  Whatever data you pass in will be bound to `scope.directiveData` inside of the rendered template.

**Comment by azaslavsky** [comment]
Thank you!

**Comment by Stabzs** [comment]
You're welcome!
