### ISSUE TITLE
body output type - directive is not working

### ISSUE THREAD

**Issue by rdheepan** [jirikavi/AngularJS-Toaster#159]
I am trying to create toaster pop-up using directive and it's not showing the directive data. Instead it just show the directive name. Take a look this [Plunker](http://plnkr.co/edit/V6vybEIek15ybVsYcF3P?p=preview).

**Comment by Stabzs** [comment]
Very simply, you are using the release tagged version of toaster, 0.4.15.  The directive body type was added after 0.4.15.

I have created a new release: https://github.com/jirikavi/AngularJS-Toaster/releases/tag/0.4.16 so that you can use a properly tagged release with the new directive functionality. 

Thanks!
