### ISSUE TITLE
Attach bidirectional data to template

### ISSUE THREAD

**Issue by brentahiti** [jirikavi/AngularJS-Toaster#163]
I'm trying to implement a feature where I would need bidirectional data attached to the template.

As for now, the directive uses '@' for directiveData and I'm not sure how to use 'templateWithData' bodyOutputType. It awaits an expression which looks into the scope. I would have thought that some data could be passed to the template with that option.

Am I missing something?

**Comment by Stabzs** [comment]
I would be extremely cautious about binding bidirectional data to a toast template.  Toasts should not contain large amounts of business logic but should rather be informative in nature.  

By design, the directive bodyType is designed to be a one way channel between the parent that pops the toast (with the corresponding data) and the customized directive that is compiled by directiveTemplate and subsequently binds the data.  There is no binding between the parent and the toast at that point so data could not be propagated up.

If you could put together a Plunker or a JSFiddle that illustrates what you are trying to do, it will be easier to identify if it is an abuse of the design, a bug, or a misunderstanding.

**Comment by brentahiti** [comment]
This is what I'm trying to do (simplified):
http://plnkr.co/edit/sXCOkvX1fpPFC5lv8puB

**Comment by Stabzs** [comment]
Whenever you are sharing state like this, it is usually best to use events (see my very quick, primitive example http://plnkr.co/edit/RLA0qBb4FGGgXu0lvvGn?p=preview), $watch on the parent, or $watch via a shared service.  Allowing the directive access to your parent would probably be inadvisable behavior (not to mention not possible by design).

**Comment by brentahiti** [comment]
reading the code a little bit more makes me realize the toaster-container isn't intended to be global. any design insights on this?

**Comment by Stabzs** [comment]
I did not write the toast-container and there have been several revisions since it was originally written that have continuously redefined it's functionality.  That said, I think that the correct approach is to not globally expose the inner workings of the toast-container but rather expose a concrete API that allows for clear and consistent behavior.  I am not advocating that the current API handles every case appropriately, but overall I think that it is fairly consistent.

I'm curious to here what you think would need to be added to give you the type of "global" behavior that you are working for.  In the interest of single toast instances having a defined scope, I think that a shared service appropriately handles the above situation that you described without the need to expose any additional scope.  This is partially why the directive bodyType was added...to give fine-grained control over a toast on a toast-by-toast instance without toast-container needing to get involved in the behavior of the template of the toast.

 Perhaps this is becoming an x-y problem.  You really want behavior y, but you are asking about issue x in an effort to get y.

**Comment by brentahiti** [comment]
Since a toast's behavior is imo somewhat global, I was trying to use it as so. But in this implementation, toasts are meant to be used locally on the scopes you want to use them. I find it a little bit counter intuitive, but maybe it is just me.

I'm not asking for any added behavior, but just wondering why it was done like that. I used one of the solutions you provided earlier btw. Thanks for helping out

**Comment by Stabzs** [comment]
I understand where you're coming from :).  I think the approach as a whole has to been to provide only what is needed rather than providing everything that is available.

Happy to help.
