### ISSUE TITLE
Feature: Setting default message for specific type

### ISSUE THREAD

**Issue by saadshahd** [jirikavi/AngularJS-Toaster#166]
Hi,

I noticed that this snippet is repeated a lot in my app:
```
var message = data.message || 'Something went wrong';
toaster.pop('error', null, message);
```

So it would be better if I could set default message for the type `error`

**Comment by Stabzs** [comment]
I'm not certain that I agree.  How would the toaster API handle a default error message and how would it determine when to call it?  The only thing I can think of off the top of my head is by adding a configurable option that allows you to set a default message that would be used in the case of a message argument not being added for that type.

That said, I am still not convinced that that is an intuitive API.  It seems to me that you should instead consider writing a service that contains your boilerplate default methods and your default message.

**Comment by saadshahd** [comment]
I imagined it to be like this

at the views:
`<toaster-container toaster-options="toasterOptions"></toaster-container>`

and controllers:
```
$rootScope.toasterOptions = {
  'default-messages': {
    'error': 'Something went wrong'
  }
 }
```

**Comment by Stabzs** [comment]
Agreed, the configuration would be something like your example above (although personally I would recommend against using default $rootScoped objects for your configuration).

That said, the interaction with the API is still a bit confusing and misleading, not to mention it delegates a lot of responsibility to the library.  Based on your above example, would the default be called for whitespace?  Empty strings?  Null?  Undefined?  If a falsey evaluation was used, in the case where your message was an object it would be true and would not call the default.

This feels like unnecessary complication for little benefit and once again I'd advocate for wrapping your toaster calls in a small service that allowed you to manage your own default error message fallbacks rather than "polluting" the API with a feature that I tend to think would not be often utilized.  That said, I'm happy to hear your arguments to the contrary as well as community feedback :)

**Comment by saadshahd** [comment]
Thanks for replying,
What do you recommend to use for configuration instead of rootScope ?

The feature does not have to work if passed message was not a falsy value.
I was trying to get into the toaster.js core to come with PR but I got confused about bodyTemplates.

What I imagined to be in toaster.js end `message = title || message ? message : defaultMessages[type] ` 

I will think about wrapping this in my code for now :dart:

**Comment by Stabzs** [comment]
It is always ideal to inject as close to the directive's scope as possible, which is typically inline (in your html).  It is also very transparent that you are overriding the default configuration.  However, if you did need to share the same configuration across multiple toaster container instances, a common scope would be best.

To elaborate a bit more on my example, think of the following scenarios.

A service errors and you want to use a toast to display an error message:
a.  error.message is 3.  In this case message would be truthy and your default would not be used.
b.  error.message is { brief: '', details: '' }. In this case message would be truthy and your default would not be used.
c. error.message is ''.  In this case message would be truthy and your default would not be used.

My point is that you would have to delegate the responsibility to toaster.js to know whether or not it should consider any of these cases valid, which may not be the same for every user.  If it was wrapped in your code BEFORE calling toaster, you could determine the validity of the message.
