### ISSUE TITLE
Toaster Message is displayed after clicking on some controls in page

### ISSUE THREAD

**Issue by ompanda** [jirikavi/AngularJS-Toaster#168]
I am adding a toaster for page. The desired behavior is it should be displayed immediately. But the toaster message is displayed once i click on some controls in that page. I am not using any delay in toaster configuration. It seems an issue with browser event loop. I have tested this in chrome not in other browsers.

**Comment by Stabzs** [comment]
Most likely you are triggering your toast outside of an angular digest cycle, which is not a bug but normal behavior for angular. 

Please post a link to a jsfiddle or plunker of what you have tried and I will be happy to take a look.

**Comment by ompanda** [comment]
Thanks for reply.You have a valid reason. but  i am not adding it outside of digest cycle. i have gone through toaster.js code but did not get anything what exactly causing this issue.

**Comment by Stabzs** [comment]
There is nothing that WOULD cause the issue you're describing in the toaster code.  There have historically been two reasons for the type of behavior that you are describing:

1.  Your toaster-container is located inside of your ng-view, causing it to change between views, requiring a digest cycle to trigger an update.  I would advocate that in most instances the container should be placed higher in the DOM than inside of individual ng-view components (same principle applies for ui-router).

2.  You are forcing a pop outside of the angular digest cycle (such as calling it from `$(document).ready()`), which means that your toast will not show up until you force a digest cycle.  In most cases however, this is incorrect as well since if at all possible, you should trigger angular libraries via angular APIs and not by forcing a manual digest.

In either case, I can't actually help you resolve this without a demonstration of what you are currently doing.  Please provide a small, complete jsfiddle or plunker that demonstrates the behavior and I'll be happy to take a look.
