### ISSUE TITLE
Toaster does appear twice when called from modal view.

### ISSUE THREAD

**Issue by ekiziltas** [jirikavi/AngularJS-Toaster#181]
Dear All, I have really hard issue about calling a toaster from ui-modal.That is, if you define toaster containers in both modal calling screen and ui-modal, then toaster popups appear twice, as it is detailed earlier with the issue number #132. However, toaster container should be capable of allowing toaster message to display only in the current active view (which is supposed to be in modal view not in the modal calling view).

As far as I investigate the earlier issues, I have only found one closed issue (#132) which is closed with the solution of declaring container once, but I think there is a necessity to cover this need globally not interim solution.Since, as a addicted user of AngularJS-Toaster, I have linked lots of workflows with the callback function of the messages and it is inevitable that this capability would be the basics of the toaster in near future.

Regards.

**Comment by Stabzs** [comment]
If you insist on using two unique `toast-container` elements, you can (and in your case should) use unique toaster ids per container since that way you can deliberately target a container.

Now, that said, if you use the same 'animation' position, they'll simply layer over one another and then you'll be unable to see your second toasts.  However, based on what you've described, it sounds like you've already dealt with this issue.

I've created an example for you here:  http://plnkr.co/edit/4ICtcrpTSoAB9Vo5bRvN?p=preview

As an aside, I absolutely disagree that the library should be responsible for understanding the state of the "view" layer of your application.  It shouldn't care what the active view is, where the active view is, or how you define active view.  Rather, you should maintain your views and use the tools the library has at it's disposal to properly target the correct container.

Hope this helps.

**Comment by ekiziltas** [comment]
Works perfect. Thank you :+1:

**Comment by Stabzs** [comment]
Happy to help!
