### ISSUE TITLE
Add handler to clear toasts

### ISSUE THREAD

**Issue by phillipgreenii** [jirikavi/AngularJS-Toaster#202]
# Overview

This is related to #58, but with a simpler use case.  Currently, `toaster.pop()` doesn't return anything.  My suggestion is to make it return a handler that could be used to clear the specific toast message that was generated.  A usage example is as follows:
```javascript
var handler = toaster.pop('close me!');
handler.clear();
```
## Simplistic Implementation
```javascript

function($rootScope, toasterConfig) {
    this.pop = function(type, title, body, timeout, bodyOutputType, clickHandler, toasterId, showCloseButton, toastId, onHideCallback) {
        // current implementation stays the same
        // but not displayed for this example to save space
        $rootScope.$emit('toaster-newToast', toasterId, toastId);
        // new code starts here
        var toast = this;
        handler = {
            clear: function() {
                toast.clear(toasterId, toastId);
            }
        }
        return handler;
    };

    this.clear = function(toasterId, toastId) {
        $rootScope.$emit('toaster-clearToasts', toasterId, toastId);
    };

}
```
# Problems
It is unclear what should happen when a `toastId` is not specified.

## No special handling
In this situation, the call to `toast.clear` would cause any message that didn't specify a `toastId` to be cleared.  This seems to violate the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

## Generate a surrogate key for all toasts.
In this situation, `toast.pop` could be updated so that if `toastId` is not specified, then one would be generated.  This ensures that `handler.clear()` will only clear the associated toast.  However, I don't know if this would break other parts of the code base.

## Throw an error
In this situation, if the `toastId` is not specified, then `handler.clear()` throws an error.  This seems to be acceptable.

# Summary
For my needs, any of the outlined solutions would work.  Can someone who is closer to the project provide direction on which solution if any should be implemented?

**Comment by Stabzs** [comment]
Thank you for creating this excellent summary issue of our longer discussion on https://github.com/jirikavi/AngularJS-Toaster/issues/58.  

I've been giving this issue (and the related issue) quite a bit of consideration.  I think your synopsis is quite accurate, as are the current issues and potential solutions that you've laid out.

That said, I believe that the underlying problem is that the toastId simply cannot be known or guaranteed (currently) when pop is called.

I fought the same issue on my angular2-toaster implementation and after a good deal of thought, I decided that the real solution is to generate unique `GUID` ids in the [calling service](https://github.com/Stabzs/Angular2-Toaster/blob/master/src/toaster.service.ts#L57), rather than allow each container to maintain their own ID counters.  This is ideal since even in our AngularJS, $emit-driven implementation, we can generate the ID before emitting/broadcasting which allows us complete control over returning back that toastId in all pop circumstances.

# Negatives
* All code that uses a self-incrementing-per-container toastId will need to be modified
* All associated tests that check Ids will need to be updated.
* A GUID string would need to be used, stored, and returned for every toast instance.  Some may not like this nearly as much as they like a number and it is larger.
* While I believe the GUID solution I chose in Angular2-Toaster will nearly guarantee Randomness (and I couldn't produce a collision in 5 million generations) there is always a chance it won't be perfectly random, although incredibly unlikely.
* Fully breaking change

# Positives
* Truly unique toastIds.
* One generated toastId would be shared across multiple containers in the case of broadcasting to multiple containers, making chance of a numeric collision extremely unlikely and removes the need to choose strange Ids to avoid collisions.
* Removes the need to ever provide a toastId argument which cleans up the API.
* Closes all (or nearly all) currently open issues and removes the largest thorn in the side of the library.

I would love to hear your feedback.  If you believe that this is a terrible solution for the problem, lets discuss alternatives.  I would like to solve more than just the close handler issue and while any of the above described solutions could work, i think this may be a vastly superior solution.

**Comment by phillipgreenii** [comment]
I agree with your summary and conclusions.  In my mind, autogenerating the id is necessary to both simplify and expand the API.  However, I try not to jump into other people's code bases and ask them if they could significantly change their implementation.  I'm glad you have considered this before and are more aware of the ramifications.  The only thing that I would point out is that (at least for now), I don't think you need to completely remove the ability for users to specify their own IDs.  I don't see why it can't be coded to accept user ids and if not, default to GUID generation.  Of course conflicts could arise, but that is no different than today.  Should we create a branch for this to see what things will look like? Or am I rushing things?

**Comment by Stabzs** [comment]
@phillipgreenii Please see the associated branch check-in.  It may remove the need to have a `handler.clear()` function.  If still useful, it could be added in as well.

**Comment by phillipgreenii** [comment]
I think your branch is the way to go.  It is more inline with the rest of the API.  My only suggestion would be to override `toaster.clear()` so that I could do the following:

```javascript
var toast = toaster.pop('close me!');
toaster.clear(toast);
```

**Comment by Stabzs** [comment]
@phillipgreenii that's very reasonable.  I've gone ahead and added in that feature as well.  In addition, I added support for each of the toaster pop helper methods.

**Comment by Stabzs** [comment]
@phillipgreenii Release 2.0.0 has been merged and published to npm.

**Comment by Stabzs** [comment]
You're welcome!  Thanks for the valuable input!
