### ISSUE TITLE
RequireJS and AngularJS-Toaster doesn't work together

### ISSUE THREAD

**Issue by Dekamerron** [jirikavi/AngularJS-Toaster#209]
```
(function () {
    require.config({
        paths: {
            'angular': 'bower_components/angular/angular',
            'jquery': 'bower_components/jquery/dist/jquery',
            'toaster': 'bower_components/toaster/toaster'
        },
        shim: {
            angular: {
                deps: ['jquery'],
                exports: 'angular'
            },
            toaster: {
                deps: ['angular', 'jquery'],
                exports: 'toaster'
            }
        }
    });

    require([
        'angular',
        'app',
        'toaster',
        'jquery'
    ],
    function (angular, app, toaster) {
        'use strict';
        // toaster is undefined. I add it here just for a check. <<<<<<

        angular.bootstrap(angular.element('body')[0], ['myApp']);
    });
})();
```

This is main.js and toaster is undefined where I wrote the comment near the end. The file is loaded as I can see it at Sources tab in the console. 
In addition, wherever I want to use 'toaster', it is undefined. Here some code from the same demo app:

First case:
```
define(['somefile', 'toaster'], function (someModule, toaster) {
	'use strict';

	// toaster is undefined

});
```

Second case (John Papa Angular Style Guide):
```
define(['somefile', 'toaster'], function (someModule) {
	'use strict';

	someModule.controller('NewController', NewController);

    NewController.$inject = ['someDeps', 'toaster'];

    function NewController(someDeps, toaster) {

	// angular.js:13424 Error: [$injector:unpr] 
    // Unknown provider: toasterProvider <- toaster <- NewController

    }
});
```

Can anyone tell me what I'm doing wrong?

**Comment by Stabzs** [comment]
I'm not certain why you would expect that they would.

Mixing RequireJS and AngularJS in and of itself isn't exactly something I'd recommend, although it's doable.

However, mixing RequireJS and AngularJS-Toaster simply doesn't make sense, nor does it work.  In order to be imported by Require, there needs to be *some* sort of amd-style module wrapper declaration syntax that is available for Require to hook into.  AngularJS-Toaster does NOT provide such a module wrapper nor will it ever provide such a module wrapper.  It is designed to be specifically imported by Angular.

Which leads us to the next piece of the puzzle.  Currently, you are trying to use Require to manage dependency injection for Angular.  That's not a good idea.  AngularJS has an incredibly rich and powerful module and DI resolution system that you should be taking advantage of.

What does this mean for you?  You need to load up the AngularJS-Toaster `toaster.js/min.js` source file.  How you do that is up to you and if you choose to use RequireJS, so be it.  It's imperative that it loads after angular.

Since you are manually bootstrapping, instead of having RequireJS provide dependencies, you should allow Angular to do so.  You need to register it in your app initialization:

    var app = angular.module('myApp', ['toaster'])

Now you are registered and ready to go.

    function (angular, app) {
        'use strict';
        angular.bootstrap(angular.element('body')[0], ['myApp']);
    });


Once again, I'm not sure why you're mixing Require and Angular module imports, but I wouldn't necessarily recommend it.  That said, your injection via *Angular* should now work.

```
define(['somefile'], function (someModule) {
    'use strict';

    someModule.controller('NewController', NewController);

    NewController.$inject = ['someDeps', 'toaster'];

    function NewController(someDeps, toaster) {
        toaster.pop();
    }
});
```

Be very careful when mixing libraries and functionality in this way.  It can lead to a TON of headaches if you're not careful.

**Comment by Stabzs** [comment]
This is not an issue with the library itself and I am closing the issue.  However, feel free to continue dialog in the comments if you need additional assistance.

**Comment by Dekamerron** [comment]
Working as expected.
