### ISSUE TITLE
Position not being set when initialized

### ISSUE THREAD

**Issue by blake-nouribekian** [jirikavi/AngularJS-Toaster#212]
I need to be able to control the position dynamically in the controller, not the view. I have tried adding 'position-class': 'toast-top-full-width' to the initialization object of toaster but it is not working.

`
toaster.pop({
						type: 'success',
						title: '',
						body: 'Some text',
						bodyOutputType: 'trustedHtml',
						'position-class': 'toast-top-full-width',
						showCloseButton: true,
						timeout: 3000
					});
`

`
<toaster-container toaster-options="{'time-out': 1000}"></toaster-container>
`

**Comment by Stabzs** [comment]
Toasts are not configurable via `position-class` on a per toast instance.  This is because it isn't the toast that is positioned, but rather the container that holds the toast.

As a result, if you needed to do something like this, I'd recommend creating multiple `toaster-containers`, each with their own ids and specific positions.  Then, depending on the position you need, target that container.

**Comment by blake-nouribekian** [comment]
OK great! That sounds like a good plan. Thanks for the quick response.

**Comment by Stabzs** [comment]
You're welcome!

**Comment by lacerdanycolas** [comment]
> OK great! That sounds like a good plan. Thanks for the quick response.

Blake-nouribekian, how do you target multiples container with each one instances of toast? Help Please ;)
