### ISSUE TITLE
Why is there no compile + scope option?

### ISSUE THREAD

**Issue by Narretz** [jirikavi/AngularJS-Toaster#219]
I'm a bit puzzled why there isn't a simple option for the toast to use a template string / templateUrl, pass in a scope, and have that compiled, similar to uib-modal for example: https://angular-ui.github.io/bootstrap/#/modal

Instead, there is the "directive" option, that is basically an indirect way of doing this. You can easily create a wrapper directive that creates a new scope, assings the directiveData to it, and compiles arbitrary content and appends it to the toast. 

So I wonder why is there no direct way of doing this? If you are able to compile the content, then you have all the options, including adding arbitrary directives.

**Comment by Stabzs** [comment]
Is there a particular use case that you are looking for that the current approach cannot accommodate? 

When originally requested (and added) the design perspective was that of a directive-first approach, since this is more flexible than needing to pass in a template url and handles cases such as the directive not existing a bit better, giving more feedback over the process.  This favors the current popular approach of heavy componetization, allowing encapsulated directives to drive behavior instead of templates.

Now that said, this is simply the current state of the design.  It doesn't have to be the only state of the design. If the current state is not accommodating a need of yours (not a preference, but a need), then it seems more than reasonable to look at additional methods of template resolution for embedding content in a toast dynamically.

**Comment by Narretz** [comment]
The current options allow all of my use cases, but the fact that you dynamic content must be done with a directive that cannot create a scope etc. makes everything more complicated than it has to be, and introduces limitations and caveats that are not obvious and must be documented specifically, see. Now you need special support for components, because of the implementation: https://github.com/jirikavi/AngularJS-Toaster/issues/221 Wouldn't be necessary if I could simply take a template and compile it with a scope I choose.

See it like this: the compiler in Angular takes any template and links it with a scope. Directives are built on top of that. Directives are not the core concept, compilation and scope is. The current implementation is too specific and does not reflect core Angular concepts.
