### ISSUE TITLE
Support for untrusted HTML

### ISSUE THREAD

**Issue by insanicly** [jirikavi/AngularJS-Toaster#280]
Hi, 

Can we add a new option to bodyOutputType since sometimes we might not want to use $sce.trustAsHtml for our html. When you use that it makes our toast vulnerable to XSS attacks. 

I can create a PR for you if you want that.

**Comment by insanicly** [comment]
Hi @Stabzs ,

Actually, ng-bind-html is already sanitizing the input given to it, here is the reference:

https://docs.angularjs.org/api/ng/directive/ngBindHtml

when you call $sce.trustAsHtml you are disabling the sanitization and marking the html as safe. 

I need an option for bodyOutputType that redirects my input to ng-bind-html without trusting it. 


Actually this statement in your readme is wrong or I am missing something you are doing 

> trustedHtml: When using this configuration, the toast will parse the body content using $sce.trustAsHtml(toast.body). If the html can be successfully parsed, it will be bound to the toast via ng-bind-html. If it cannot be parsed as "trustable" html, an exception will be thrown.

Calling $sce.trustAsHtml is not a way to check if the input can be trusted. It is a way that blindly marking the input as trusted.

see ref:
https://docs.angularjs.org/api/ng/service/$sce#trustAsHtml
this is going to here:
https://docs.angularjs.org/api/ng/service/$sceDelegate#trustAs

see the explanation:
> This trusted object will later on be used as-is, without any security check, by bindings or directives that require this security context. For instance, marking a string as trusted for the $sce.HTML context will entirely bypass the potential $sanitize call in corresponding $sce.HTML bindings or directives, such as ng-bind-html. Note that in most cases you won't need to call this function: if you have the sanitizer loaded, passing the value itself will render all the HTML that does not pose a security risk.

**Comment by Stabzs** [comment]
You are completely correct, my apologies.  I haven't looked at the docs in a very long time and my memory was very fuzzy.

I agree with your assessment and the need to add a new option to bind the html without trusting it explicitly.

In order to preserve backwards compatibility as much as possible, I think leaving the `trustedHtml` output type is still appropriate...we should only render it if actually trust the html, although the AngularJS-Toaster documentation needs to be updated to properly represent the security risk.  A new `html` bodyOutputType can be added that will bind directly to `toast.html`. 

This brings up an interesting problem in that the toast button can be bound as html and currently bypasses the sanitizer as well.  This becomes a little bit more problematic from an API perspective since there's currently no API to indicate whether or not the content can bypass the sanitizer.  One option is to remove the check and push the responsibility back onto the consumer to ensure that their content is either safe or sanitized.  This would be a breaking change (and the library is overdue for a major version) but it is probably worth it in light of this discussion.

Thanks for bringing this up!

**Comment by Stabzs** [comment]
Based on how the closeHtml is currently being utilized, at this point in time I'm going to leave it with an untrusted call.  If there's a lot of interest down the road I can look at adding an additional configurable override for this behavior.
