### ISSUE TITLE
Toasts won't show up under certain conditions

### ISSUE THREAD

**Issue by deborasetton** [jirikavi/AngularJS-Toaster#72]
Hi,

I'm trying to understand an issue that ocurred when I was trying out AngularJS-Toaster like shown below. I'm aware this is _not_ the way to use it, I was just trying to experiment in the Chrome console:

```javascript
  angular.module('DemoApp').controller('demoCtrl', function($scope, toaster) {
    window._toaster = toaster;
    _toaster.pop('success', "title", "text");
  });
```

What happens is that I can call ` _toaster.pop('success', "title", "text");` 20 times in the console, and no toast will show up until the first toast that was created is destroyed after its timeout.

To better understand this, I put together a simple demo, [here](https://gist.github.com/deborasetton/72f0b52b6758588ceec8).

I don't know if the problem is related to AngularJS scoping, or linking the directive, or something else.

I'm using the master version of toaster.js with AngularJS 1.2.0, if that helps.

Thank you!

**Comment by minirobotdan** [comment]
I'm also experiencing this, and I think it has something to do with $location.path(). Whenever the my application change's the location using this method (for me it's on a 401 in the auth interceptor and during a logout), the first toast to be fired off after this change does not materialise.

**Comment by minirobotdan** [comment]
More weirdness regarding this issue, we have several instances in our application where the error callback on a $resource won't trigger a toaster inside it, unless I console log the error in the line above. 

Here's an example from our application:

		Job.save({report: payload}, function(data) {
			toaster.pop('success', 'Success', 'Report scheduled successfully.');
		},function(error) {
         // This toast won't pop
			toaster.pop('error', 'Error', 'Unable to schedule report- ' + error.data);
		});

Here's the working version...

		Job.save({report: payload}, function(data) {
			toaster.pop('success', 'Success', 'Report scheduled successfully.');
		},function(error) {
        // This toast pops fine...
			console.log(error);
			toaster.pop('error', 'Error', 'Unable to schedule report- ' + error.data);
		});

The only thing i can even thing is going on here is there's some under the covers promise pattern optimisation going on in Chrome, and console logging that variable is jogging it to complete when it would otherwise get stuck somehow. I've had a look through the code for this module and can't see anything blindingly obvious that would cause this.

One more observation- placing the console.log after the toaster statement also solves it, but it seems to take longer.

**Comment by jeffreynolte** [comment]
+1 on this issue. I am using toaster in a similar way to you @minirobotdan:

```javascript
vm.updatePhoto = function(photo){
      dataservice.updatePhoto(photo).then(function(res){
        toaster.pop("success", "Success", "Photo Successfully updated");
        photo = res;
      });
    };
```
While my issue does not have to do with console it is moreso an issue with url / hash change but I feel they can be related.  When I change routes in my app (controller is shared between routes) I get a similar issue where `toaster.pop` will only work on the route which was initially loaded (changing routes makes it so it stops working).

**Comment by olso** [comment]
@jeffreynolte thanks for the alternative repo

**Comment by Avcajaraville** [comment]
I was having the same issue till I did scope.$apply around the toaster call.

Depends on your use case, it might help

**Comment by Stabzs** [comment]
@deborasetton Your problem (while perhaps related to the other reported issues), is unique because of how and when you are calling the toast.  By invoking toaster off of window (not $window, mind you), you are firing events that will add the toast instance to scope.toasters = []; internally, but angular is not aware that a digest cycle has occurred and that it is now responsible for updating appropriate bindings (in this case, displaying the toast).

How do you fix it?  In your particular case, simply use $timeout instead of setTimeout, since $timeout will call $scope.$apply() to trigger the appropriate digest call.

```js
angular.module('DemoApp').controller('demoCtrl', function($scope, toaster, $timeout) {
    window._toaster = toaster;
    $timeout(function () {
      console.debug('Calling toaster');
      _toaster.pop('success', "title", "text");
    }, 1000);
  });
```

**Comment by Stabzs** [comment]
@minirobotdan  Would you be able to put together a small repo that demonstrates your use case?  Thank you!

**Comment by Stabzs** [comment]
@jeffreynolte The reason that the alt repo works in your use case is because they explicitly call $animate, rather than allowing the applied css3 transitions to work on their own, which is one of the major features of this particular implementation. As a result, it will always apply the appropriate digest cycle, even in your case.  If you could please create and provide a small repo describing your particular use case where you want to pop a toast within a service promise callback, I would be happy to take a look at it. 

Thanks.

**Comment by deborasetton** [comment]
@Stabzs Thanks for the reply! I ended up using `$timeout` indeed, but I wasn't sure _why_ that worked, so thanks for the explanation.

I'm not sure about the other cases described above but, as far as I'm concerned, feel free to close the issue.

**Comment by Stabzs** [comment]
@deborasetton Thanks for the quick response!  I was happy to give a quick explanation and I'm glad that that explanation was consistent with your solution.  

If no additional details are reported on this issue, I'll close it.  Thanks.
