### ISSUE TITLE
First toast appears correctly, all others appear with the same color

### ISSUE THREAD

**Issue by zyadsherif** [jirikavi/AngularJS-Toaster#77]
Hi am having a problem where only the first toast after refreshing the page would work with the correct type param, all following toasts just default to the blue color which is the info type.

**Comment by Gamaroff** [comment]
I am also having the same problem.

**Comment by jirikavi** [comment]
Hi,
I did some fixes in latest commit so you also your bug might be fixed.
Jiri.

**Comment by zyadsherif** [comment]
@jirikavi updated to the latest push, still no luck.

**Comment by jirikavi** [comment]
Hi,
That is weird, Can you provide some plunk with this issue?
Jiri

**Comment by Gumarelo** [comment]
I'm having the same problem.

All is in blue

Automatically is generating 

<div ng-repeat="toaster in toasters" class="toast ng-scope toast-info" ......>

**Comment by irongomme** [comment]
Same for me when called from a nested controller ... otherwise all is good !

**Comment by deantomasevic** [comment]
Same here.
All is in blue.

It works after i refresh the site and create a new toast.

**Comment by miro** [comment]
Same problem here, all the toasts work fine besides the type parameter has no effect on them; all are rendered with the "toast-info" -class. It doesn't matter if I pass the parameters inside an object or as strings.

My app is fairly simple, and it is based on [this boilerplate](https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate), so I load Toaster through browserify.

This seems to be somehow related to the configuration of the Angular app/something else rather than changes in the Toaster itself. I am using Toaster on other project without browserify without issues, and there the version I had downloaded earlier was 0.4.7 - using that version with my current app resulted in same results, all the toasts are "info"-toasts.

**Comment by miro** [comment]
Actually with some fiddling around I managed to solve the issue on my own case, not sure if I was misusing the Toaster or what, but:

I'm using the ui-router, and I placed the toaster-container like this:

      <toaster-container></toaster-container>
      <div ui-view class="container-fluid"></div>

Moving the `toaster-container` inside `ui-view` fixed the issue.

**Comment by irongomme** [comment]
Thanks @miro 

This makes me realize that i had duplicates toaster-container, and this was the reason for this bug for me !

**Comment by KimSunWook** [comment]
Very Good! I solved this problem! Thanks @miro !

<body ng-app="MyApp" controller="MyCtrl" class="...">
   <ion-nav-view class=""></ion-nav-view>
   <toaster-container></toaster-container>  
</body>

**Comment by Stabzs** [comment]
This seems wholly related to either multiple toast-containers or placing the toast-container at the wrong level.  For future reporting of this issue, please provide a complete plunkr or jsfiddle as a new issue.
